server:
  port: 8201
  servlet:
    context-path: /api
spring:
  application:
    name: service-hosp
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kkgh_hosp
    username: root
    password: 123456
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
knife4j:
  enable: true
  openapi:
    title: service-hosp
    description: "医院设置模板"
    version: v1.0.0
    license: Apache 2.0